config/routes.rb
Rails.application.routes.draw do

  root :to => 'homes#top'
  
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord



  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @books = Book.all
  end

  def create


    @book = Book.new(book_params)


    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)

    else
      @books = Book.all
      render :index
    end

  end

  def index
    @books = Book.all
    @book = Book.new


  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)

      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)

    else
      @books = Book.all
      render :index
    end


  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>






<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

<p>Title</p>
<%= f.text_field :title %>

<p>Body</p>
<%= f.text_area :body %>

<%= f.submit 'Update Book'%>

<br>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>


<% if flash[:notice] %>
<p id="notice">
  <%= flash[:notice] %>
</p>
<% end %>


<% if @book.errors.any? %>

  <%= @book.errors.count %>件のerrorが発生しました。

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>


<div class="main">
<table >
  <thead >
    <tr class="nav">
      <th class="nav-list">Title</th>
      <th class="nav-list">Body</th>
      <th colspan="3" class="nav-list"></th>
    </tr>
  </thead>

<% @books.each do |book| %>
  <tbody>
    <tr>
      <td>
        <%= book.title %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td>
        <%= link_to "Show", book_path(book.id) %>
      </td>
      <td>
        <%= link_to "edit", edit_book_path(book.id) %>
      </td>
      <td>
        <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
      </td>
    </tr>
<% end %>
  </tbody>


</table>




<h2>New book</h2>

<%= form_with model: @book do |f| %>

  <p>Title</p>
  <%= f.text_field :title %>

  <p>Body</p>
  <%= f.text_area :body %>
  <br>

  <%= f.submit 'Create Book' %>

<% end %>
</div>

app/views/books/new.html.erb
<p>Book was successfully created.</p>


<% if @books.errors.any? %>

  <%= @books.errors.count %>件のエラーが発生しました。

  <ul>
    <% @books.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>




    <% @books.each do |book| %>

<p>
  <strong>Title:</strong>
  <span>
    <%= link_to book.title, "/books/#{book.id}" %>
  </span>
</p>
<p>
  <strong>Body:</strong>
  <span>
    <%= link_to book.body, "/books/#{book.id}" %>
  </span>
</p>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p id="notice">
  <%= flash[:notice] %>
</p>
<% end %>

<p>
  <strong>Title:</strong>
  <span>
    <%=  @book.title %>
  </span>
</p>
<p>
  <strong>Body:</strong>
  <span>
    <%= @book.body %>
  </span>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそBookersへ</h1>



<p><strong>Bookers</strong>ではさまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます。</p>



<span>
<%= link_to 'start', books_path %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>